 * Running on http://0.0.0.0:5000/
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    app.run(debug = True,host='0.0.0.0')
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 739, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 706, in run_simple
    test_socket.bind((hostname, port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
